"""add exchange rate bulletin date

Revision ID: 0bc5d72ab9c6
Revises: fa1245540e0e
Create Date: 2026-09-23 07:32:17.674774

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bc5d72ab9c6"
down_revision: str | Sequence[str] | None = "fa1245540e0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("requested_date", sa.Date(), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "currency_code",
            "requested_date",
            name="uq_exchange_rates_code_requested_date",
        ),
    )
    op.create_index(
        op.f("ix_exchange_rates_currency_code"),
        "exchange_rates",
        ["currency_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rates_rate_date"),
        "exchange_rates",
        ["rate_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rates_requested_date"),
        "exchange_rates",
        ["requested_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_requested_date"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_rate_date"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_currency_code"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
