"""finalize statement import

Revision ID: 5123255f7267
Revises: 7b5a35617841
Create Date: 2026-09-22 23:29:56.232438

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5123255f7267"
down_revision: str | Sequence[str] | None = "7b5a35617841"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statements",
        sa.Column(
            "content",
            sa.LargeBinary(),
            server_default=sa.text("''::bytea"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("statements", "content")
    # ### end Alembic commands ###
