"""add statement imports

Revision ID: 7b5a35617841
Revises: 5d74cfe6971f
Create Date: 2026-09-22 23:19:51.021530

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b5a35617841"
down_revision: str | Sequence[str] | None = "5d74cfe6971f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("imported", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'done', 'failed')", name="ck_statements_status"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statements_account_id"), "statements", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_statements_user_id"), "statements", ["user_id"], unique=False
    )
    op.add_column(
        "transactions", sa.Column("fingerprint", sa.String(length=128), nullable=True)
    )
    op.create_index(
        op.f("ix_transactions_fingerprint"),
        "transactions",
        ["fingerprint"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_fingerprint"), table_name="transactions")
    op.drop_column("transactions", "fingerprint")
    op.drop_index(op.f("ix_statements_user_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_account_id"), table_name="statements")
    op.drop_table("statements")
    # ### end Alembic commands ###
