"""add budgets and budget events

Revision ID: b83c6595105f
Revises: 0bc5d72ab9c6
Create Date: 2026-09-23 07:41:18.556110

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b83c6595105f"
down_revision: str | Sequence[str] | None = "0bc5d72ab9c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("limit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_id", "month"),
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_table(
        "budget_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("limit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("spent", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_events_budget_id"), "budget_events", ["budget_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_events_created_at"),
        "budget_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_budget_events_user_id"), "budget_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_budget_events_user_id"), table_name="budget_events")
    op.drop_index(op.f("ix_budget_events_created_at"), table_name="budget_events")
    op.drop_index(op.f("ix_budget_events_budget_id"), table_name="budget_events")
    op.drop_table("budget_events")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
